# Generated by Django 5.0.6 on 2026-07-02 06:42

import apps.recruiters.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('company_size', models.CharField(blank=True, help_text="e.g. '1-10', '11-50', '500+'", max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('about', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.recruiters.models.logo_upload_path)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
